### ISSUE TITLE
SPIM3 issues with nrf52840 (format example)

### ISSUE THREAD

**Issue by CSC-Sendance** [adafruit/Adafruit_SPIFlash#138] opened 2022-11-24 12:33 UTC
### Operating System

Windows 11

### IDE version

PlatformIO Core 6.1.5·Home 3.4.3

### Board

Feather nrf52840 express

### BSP version

1.3.0

### SPIFlash Library version

4.0.0 / 4.1.0

### Sketch as attached file if not stock example

examples/SdFat_format

### What happened ?

The example for formatting external flash memory works when using an external flash memory via SPI (in our case a W25Q128JV_SQ)  and the nrf52832. With the nrf52840 and the same external flash memory chip the example "succeeds" in formatting the chip but not mounting the file system since it cannot detect the FAT/BS partition (fmt=3). 

Switching to SPIM2 from SPIM3 via build-flag -DSPI_32MHZ_INTERFACE=1  "fixes" the issue.

**Possible cause**
This could be related to a hardware issue with SPIM3 in the nrf52840 series (see https://infocenter.nordicsemi.com/index.jsp?topic=%2Ferrata_nRF52840_Rev3%2FERR%2FnRF52840%2FRev3%2Flatest%2Fanomaly_840_198.html&cp=4_0_1_0_1_28 and https://infocenter.nordicsemi.com/topic/errata_nRF52840_Rev3/ERR/nRF52840/Rev3/latest/anomaly_840_174.html?cp=4_0_1_0_1_16 ). A similar issue appears to have caused the SPI library to do a custom nrf52832 implementation skipping SPIM altogether ( https://github.com/adafruit/Adafruit_nRF52_Arduino/blob/master/libraries/SPI/SPI_nrf52832.cpp ).

In total, this issue may be more related to the adafruit nrf52 framework's SPI library but we were able to use the SPIFlash library with a flash memory chip when not trying to format it. Hence, the issue only seems to occur on a fresh format (based on the example provided in this repository)

### How to reproduce ?

1. Connect a W25Q128JV_SQ via SPI to a nrf52840 and also the same setup with an nrf52832
2. Reconfigure the SdFat_format example to use your custom SPI pin and the default "SPI" class.
3. build & deploy the example on both setups
4. Observe the nrf52840's setup fail on the f_mount function with error code 13 (FAT not found) and the nrf52832's setup succeed.
5. Repeat the nrf52840's setup with build_flag "-DSPI_32MHZ_INTERFACE=1" to force SPIM2 instead of 3 and observe it succeeding.

**Comment by hathach** [comment] 2022-11-24 13:02
This is a known errata when using with SPIM3 https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/364. This combo of 840 + SPIM3 with external flash instead of QSPI is not used by Adafruit and therefore we won't fix this. As you already figured it out, you should use other SPIM interface instead or try to modify your linker as suggested by walkaround.

**Comment by CSC-Sendance** [comment] 2022-11-24 13:05
> This is a known errata when using with SPIM3 [adafruit/Adafruit_nRF52_Arduino#364](https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/364). This combo of 840 + SPIM3 with external flash instead of QSPI is not used by Adafruit and therefore we won't fix this. As you already figured it out, you should use other SPIM interface instead or try to modify your linker as suggested by walkaround.

Okay thanks. Maybe it's still worth a note in the README or at least a comment in the example to prevent people from having to dig for hours through the sources (like we did). What do you think?

**Comment by hathach** [comment] 2022-11-24 13:12
I known it is frustrating, though I think this issue is already served for that purpose. Also this library is cross-platform, Arduino nrf52 core already has an open issue for SPIM3 and that errata is kind of well-known one on 840.

PS: the errata may or may not be the root caused for this since we haven't confirmed it 100%. Have you tried to allocate SPIM3 with its own memory out of cpu usage as walk-around suggested ?

**Comment by CSC-Sendance** [comment] 2022-11-24 13:54
> I known it is frustrating, though I think this issue is already served for that purpose. Also this library is cross-platform, Arduino nrf52 core already has an open issue for SPIM3 and that errata is kind of well-known one on 840.
> 
> PS: the errata may or may not be the root caused for this since we haven't confirmed it 100%. Have you tried to allocate SPIM3 with its own memory out of cpu usage as walk-around suggested ?

Not yet, because the delays of this investigation have delayed my implementation efforts quite a bit, so I didn't have time to dive deeper into it yet (since I am also not 100% aware to do this right off the bat without more research and possibly without modifying the framework code). I will comment again, when/if I manage to try this workaround.

**Comment by hathach** [comment] 2023-12-18 08:54
closed due to lack of user activities, feel free to re-open it if you have update.

**Closed by hathach** 2023-12-18 08:54 UTC
Labels: Bug
